remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Le sixième sens
description: "Projet en entrepreneuriat 2023-2024 : Dans l'oeil du dragon"
logo: https://raw.githubusercontent.com/ThatAquarel/6sens/main/docs/jdlm.png